services:
  - type: web
    name: websocket-multiplayer-game
    env: node
    region: virginia
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 16.x
